### ISSUE TITLE
Duplicate apps?

### ISSUE THREAD

**Issue by gtfierro** [e-mission/e-mission-phone#164]
I see 2 "E-mission" apps in the Play store:

- "Reduce GHG emissions": https://play.google.com/store/apps/details?id=edu.berkeley.eecs.emission
- "Less GHG emissions":  https://play.google.com/store/apps/details?id=edu.berkeley.eecs.e_mission

**Comment by gtfierro** [comment]
Also, the screenshots are out of date for both of them, just so you know

**Comment by shankari** [comment]
How did you find the older app (Less GHG emissions) in the play store? I've disabled the listing

<img width="1119" alt="screen shot 2016-10-07 at 10 09 51 pm" src="https://cloud.githubusercontent.com/assets/2423263/19210549/d039e3cc-8cda-11e6-8b1e-a15aa1132d87.png">

and clicking on the direct link that you found leads to an "unavailable" page.

<img width="839" alt="screen shot 2016-10-07 at 10 11 17 pm" src="https://cloud.githubusercontent.com/assets/2423263/19210562/feae8c8a-8cda-11e6-9cc6-67e10bc7b638.png">

**Comment by shankari** [comment]
> Also, the screenshots are out of date for both of them, just so you know
Yeah, the android emulator is slow so I need to use a physical device to take updated screenshots

**Comment by gtfierro** [comment]
I just searched "emission" in the Google Play store and it showed up on the right as "similar apps":

![image](https://cloud.githubusercontent.com/assets/55434/19222126/38c37aee-8e06-11e6-8295-e92917463bde.png)

**Comment by shankari** [comment]
Hm. I don't see it in the play store listing when I check. Maybe it finally aged out?
Also, thanks for the reminder on the screenshots - I uploaded new ones now.

<img width="1437" alt="screen shot 2016-10-12 at 1 53 34 pm" src="https://cloud.githubusercontent.com/assets/2423263/19327363/78aecc88-9083-11e6-99c0-ae215f70c735.png">

**Comment by gtfierro** [comment]
![shankari](https://cloud.githubusercontent.com/assets/55434/19327419/ce68c7b4-9083-11e6-92a0-d0a6156a5db5.png)

I still see it on my desktop, but I don't see it when I view from incognito mode; its probably something I see on my account because I installed a previous version of it. I think its fine to close the issue
