### ISSUE TITLE
If party leader, I can't see other challenges

### ISSUE THREAD

**Issue by gtfierro** [e-mission/e-mission-phone#168]
In the habitica app, I can't see any "personal" challenges (e.g. take public transport, etc). Michael was able to join some of these himself, but when he opened the app today they don't appear anymore, so I can't provide you a screen shot. Am I missing something? Is there a hidden scrollbar I can't find?

![image](https://cloud.githubusercontent.com/assets/55434/19201878/9adbb31e-8c84-11e6-9f4b-83b4d90768bb.png)

**Comment by shankari** [comment]
We've disabled challenges for now.
will be enabled in the next week.

<img width="984" alt="screen shot 2016-10-05 at 3 39 09 pm" src="https://cloud.githubusercontent.com/assets/2423263/19204569/558aa58c-8c92-11e6-9772-e0e5fdbdea0d.png">
