### ISSUE TITLE
Login to the habitica website from the phone

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#177]
As far as I can determine, habitica uses the following tokens from localStorage to login.
https://github.com/sunil07t/habitrpg/blob/develop/website/client/js/app.js#L335

So if you set those values into local storage and then go to https://em-game.eecs.berkeley.edu, I think it should login.

```
      try {
        settings = JSON.parse(localStorage.getItem(STORAGE_SETTINGS_ID));
      } catch (e) {
        settings = {};
      }

      if (settings && settings.auth && settings.auth.apiId && settings.auth.apiToken) {
        $httpProvider.defaults.headers.common['x-api-user'] = settings.auth.apiId;
        $httpProvider.defaults.headers.common['x-api-key'] = settings.auth.apiToken;
      }
```

In terms of navigation, we should try these two options in order:
- navigate to a new state just like you normally do; the template has a frame with https://em-game.eecs.berkeley.edu in it. See https://github.com/e-mission/e-mission-server/blob/master/webapp/www/templates/game.html for an example. Although it would be good if the height was dynamic too. That gives the closest in-app experience
- use the in-app browser. But then you need to figure out how to return from it back to the rest of the app. You can look at my fixes for the in-app browser.
  https://github.com/e-mission/e-mission-phone/commit/534909cde6278065e665b40ce0bec517615a4a31

**Comment by shankari** [comment]
If you have to use the in-app browser, one option to return is to hack edit the habitica interface to have some kind of return button (it is javascript anyway) which navigates to a special URL and then use the trick in https://github.com/e-mission/e-mission-phone/commit/534909cde6278065e665b40ce0bec517615a4a31 to exit. Or maybe try the inapp browser with the location bar enabled or sth.

I also don't know whether the inapp browser uses the same localstorage as the main app.

But honestly, staying in the main app would be best if it works.

**Comment by krisma** [comment]
**Experiment Summary**

- Goals
When the user clicks on "More function" button, the user is navigated to the task page.

- Steps
1. Put tokens into the new page.
2. Be able to redirect to task page.
3. Be able to scroll the new page.
4. The request to task page should have "mobile" as user-agent in its header.
5. Be able to exit the new page.

- Experiments
1. iframe embedded in modal (pass token in local storage by ref $('iframe')[0].contentWindow.localstorage)
Working steps: 1, 2, 3, 5
Problem: 4 (request header can't be set in east way. could try ajax replacing content in iframe)

2. cordova webview (in app browser with target "_self" and whitelisted)
Working steps: 1, 2
Problem: 3, 4, 5 (webview is weird, when it's opened, the original index.html in inspector is gone, and the webview has no navigation buttons, so NOT recommended)

3. cordova in app browser (in app browser with target "_blank")
Working steps: 1, 3, 4, 5
Problem: 2 (reload page with js either in code or in inspector console failed, no way to reinitiate redirect after token has been injected. by inspecting local storage, we can tell the token is in there. Just that the reload is not working)

**Comment by shankari** [comment]
For experiment 3 (cordova in app browser), how do you know that step 3 (Be able to scroll the new page.) works if you are unable to reload?

Also, did you see my comments in the PR (https://github.com/e-mission/e-mission-phone/pull/187)? Can you answer the questions, in particular, `loadStart` versus `loadStop`?

**Comment by krisma** [comment]
I can scroll even on other pages, like habitica static page. step 3 simply means if the scroll bar works.

loadstart and loadstop is not the issue here. I can't even wait for it to load and reload with command in console. the first load is for same origin only, as long as the origin is set, I can execute the token injection.

**Comment by shankari** [comment]
> I can scroll even on other pages, like habitica static page. step 3 simply means if the scroll bar works.

Does the initial load work?
Did you try logging in manually to see if the tasks are loaded and the scroll works?
No point in trying to login automatically until you know that logging in manually works

> loadstart and loadstop is not the issue here. I can't even wait for it to load and reload with command in console. 

But your current code executes the script on `loadstart`. if that breaks the load, then reloading from console is not likely to work either.

I would do this step by step.
- manual login
- execute script with only alert
- execute script with alert + token set
- execute script with alert + token set + reload
...

That way you know whether the execute script actually works or not.

Another way to check the loading is to reload to a different URL that doesn't rely on the token (e.g. https://www.nytimes.com) and see whether the reload works.

**Comment by shankari** [comment]
if you are only focused on reloading, one option is to load + reload a different page, one that you control

e.g. you can load + reload http://localhost:8080 and add an alert() to the index.html served at localhost:8080

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/187 
part of release https://github.com/e-mission/e-mission-phone/releases/tag/v1.8.0
