### ISSUE TITLE
Module 'emission.main.control.collection' is not available at megumi-brt branch

### ISSUE THREAD

**Issue by sebapastore** [e-mission/e-mission-phone#430]
The error is line 4 of general-settings.js. If I comment that line, it appears a similar error with 'emission.main.control.sync' (line 5) and if I comment tha one to, it appears a similar error with 'emission.main.control.tnotify'.
![bug e-mission-phone-megumi-brt](https://user-images.githubusercontent.com/8008241/41129739-82ddffba-6a81-11e8-8b45-1ae62c23085a.png)

**Comment by shankari** [comment]
This is because you did not run the 

```
$ npm run setup-serve
```

step.

As you can see, that runs `download_settings_controls.js`, which downloads the javascript files that contain the `emission.main.control.*` modules.

```
$ npm run setup-serve
> edu.berkeley.eecs.emission@2.5.0 setup /private/tmp/e-mission-phone
> ./bin/download_settings_controls.js

Sync collection settings updated
Data collection settings updated
Transition notify settings updated
```

**Comment by shankari** [comment]
Please close the issue after confirming that the issue is resolved.

**Comment by sebapastore** [comment]
Thanks for the quick response, that was it. Sorry for the mistake.
