### ISSUE TITLE
Add frequently used controls to the main profile screen

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#50]
As we discussed on Friday, the following controls have been found to be generally useful and should be added to the main profile page:
- email logs (invaluable for debugging)
- accuracy level (main knob for tweaking power drain on iOS). Can be labelled something like "low power/lower accuracy mode"

**Comment by shankari** [comment]
@krisma this is for you :)

**Comment by krisma** [comment]
for accuracy do u mean "Select accuracy" with a bunch of KCL choices?

**Comment by shankari** [comment]
questions from slack

> I'm working on the email log. So now the func is in recent.js log ctrl, which can not be called directly in control ctrl. Two options, 1: copy paste. Ugly. Not sure if it works, hope nothing in that function is related specifically to recent log ctrl. 2: make it a service, since 2 ctrls want to access the same resource. It needs some refactoring, and might not be very necessary. What do u think?

good point. please no copy paste
6:45 I think that (2) is better
6:45 what did you find when you looked for recommendations?

**Comment by shankari** [comment]
> for accuracy do u mean "Select accuracy" with a bunch of KCL choices?
not really, I think that for the non-developer zone, a simple toggle for high accuracy versus medium accuracy is better. That should map to BALANCED_POWER_ACCURACY for android and kCLAccuracyHundredMeters on iOS

**Comment by shankari** [comment]
> So maybe named as "energy saving" or something else?

I don't really like that because it doesn't convey the sense of a tradeoff. If I see an "energy saving" mode, why wouldn't I always select it? I prefer something that indicates that there's a tradeoff - you have lower accuracy, but with lower power drain

**Comment by krisma** [comment]
resolved

**Comment by shankari** [comment]
I haven't really played around with the accuracy stuff to ensure that it works - will ask @krisma to demo on Tuesday.
