### ISSUE TITLE
EPEERINVALID

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-phone#504]
Hi,

We have been trying to develop the `trip-end prompt` to interact with server.

So we have to move from docker to traditional environment setup and installing.

Along the way, we got this error this I does not know whether it is serious or not but I cannot the Diary screen renders blank.

```
Using cordova-fetch for cordova-browser@~5.0.0


Error: Failed to fetch platform cordova-browser@~5.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm WARN invalid config loglevel="notice"
npm WARN package.json edu.berkeley.eecs.emission@2.5.0 No repository field.
npm WARN package.json edu.berkeley.eecs.emission@2.5.0 No license field.
npm ERR! Darwin 18.2.0
npm ERR! argv "/Users/atton16/.nvm/versions/node/v9.11.2/bin/node" "/Users/atton16/Desktop/emission/e-mission-phone/node_modules/.bin/npm" "install" "cordova-browser@~5.0.0" "--production" "--no-save"
npm ERR! node v9.11.2
npm ERR! npm  v2.15.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package acorn@5.7.3 does not satisfy its siblings' peerDependencies requirements!

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/atton16/Desktop/emission/e-mission-phone/npm-debug.log
```

If we switch to docker instance of phone server then it just work normally but it is more difficult to develop the feature.

**Comment by atton16** [comment]
After pulling out `npm-debug.log` from my working docker instance I found the same error. So this should no be the case that make my setup not working.

I will close the issue for now!

**Comment by shankari** [comment]
searching for EPEERINVALID (https://duckduckgo.com/?q=EPEERINVALID&t=ffab&ia=web) returns https://stackoverflow.com/questions/33816824/getting-npm-err-code-epeerinvalid-on-npm-packages-global-install

Have you checked the npm version on your traditional environment?
You need to be at the version specified in the README.

Reopening, if fixing the npm version fixes the issue, please close.

**Comment by atton16** [comment]
Updating npm version to `6.4.1` still have the same error. It looks like it cordova-browser is missing its optional dependencies (peer dependencies)

**Comment by shankari** [comment]
but that is not the version in the README. The README has 

```
$ npm -v
6.0.0
```

**Comment by shankari** [comment]
I just re-cloned the phone repository, followed the steps in the README and got no errors.

**Comment by atton16** [comment]
It looks like that phone gap use their local npm version

I have tested with both `6.4.1` and `6.0.0`

It prints out the same error so I look at the path of the npm instance, the part is from `node_modules/.bin/npm` which is the local version of npm

Even though I tried to install the local npm version 6.0.0 with `npm i npm@6.0.0`, it still prints out the same error.

I noticed that `package-lock.json` is displayed on the unstaged files on git repo. So I suspect that when I ran `npm i` to setup the project I might just got the different dependencies snapshot than yours.

Can you send me your `package-lock.json` just to confirm that I install every dependencies according to what you have ?

**Comment by shankari** [comment]
> Even though I tried to install the local npm version 6.0.0 with npm i npm@6.0.0, it still prints out the same error.

what does `$npm -v` give you?

**Comment by shankari** [comment]
> Can you send me your package-lock.json just to confirm that I install every dependencies according to what you have ?

Attached `package-lock.json` from freshly cloned repository.
[package-lock.json.gz](https://github.com/e-mission/e-mission-phone/files/2659483/package-lock.json.gz)

**Comment by atton16** [comment]
> > Even though I tried to install the local npm version 6.0.0 with npm i npm@6.0.0, it still prints out the same error.
> 
> what does `$npm -v` give you?
```bash
$ npm -v
6.0.0
$ node -v
v9.11.2
```

**Comment by shankari** [comment]
If removing `package-lock.json` doesn't work, you should consider downgrading to node v9.4.0, the version in the README

**Comment by atton16** [comment]
> If removing `package-lock.json` doesn't work, you should consider downgrading to node v9.4.0, the version in the README

It looks like the error has gone.

**Comment by atton16** [comment]
> > Can you send me your package-lock.json just to confirm that I install every dependencies according to what you have ?
> 
> Attached `package-lock.json` from freshly cloned repository.
> [package-lock.json.gz](https://github.com/e-mission/e-mission-phone/files/2659483/package-lock.json.gz)
> 
> Also, it should be safe to remove `package-lock.json` - it will be constructed if not present.

Sure that `package-lock.json` can be auto-generated but as time changes the packages version changes. This package-lock.json helps us use the same dependencies version for every dependencies to make sure that you and me install all the same deps.

**Comment by shankari** [comment]
> Sure that package-lock.json can be auto-generated but as time changes the packages version changes. This package-lock.json helps us use the same dependencies version for every dependencies to make sure that you and me install all the same deps.

Right, but that is also what `package.json` does. `package.json` contains all the installed packages with their versions. I know that there are now recommendations to check in `package-lock.json` and I am not opposed to it as long as it doesn't generate spurious review changes. But I was pretty sure that wasn't the issue here.

> It looks like the error has gone.

That's why the exact versions of the software, not just the deps, is important...

**Comment by shankari** [comment]
Also, just out of curiosity, why do you need the traditional install for editing the code? You can edit the files directly in the docker container and it should work. Is it because you want to use an IDE?

**Comment by atton16** [comment]
> Also, just out of curiosity, why do you need the traditional install for editing the code? You can edit the files directly in the docker container and it should work. Is it because you want to use an IDE?

We are trying to follow your README instructions on the host OS, that's all. The weird part is two machines produces two different issues. So right now everything is run on docker container with source code map.

**Comment by atton16** [comment]
> > Sure that package-lock.json can be auto-generated but as time changes the packages version changes. This package-lock.json helps us use the same dependencies version for every dependencies to make sure that you and me install all the same deps.
> 
> Right, but that is also what `package.json` does. `package.json` contains all the installed packages with their versions. I know that there are now recommendations to check in `package-lock.json` and I am not opposed to it as long as it doesn't generate spurious review changes. But I was pretty sure that wasn't the issue here.
> 
> > It looks like the error has gone.
> 
> That's why the exact versions of the software, not just the deps, is important...

This one fixed with `package-lock.json`.

Node version `v9.11.2` and npm version `6.4.0` run perfectly now without peer dependencies error.

But to be cautious, we use the exact version you recommended on docker just to have everything on the same version.
