### ISSUE TITLE
Wants to add few more question after mode and purpose

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-phone#514]
Is it possible to add few more questions regarding each travelled trips other than mode and purpose?
How do we reach database for that?

**Comment by shankari** [comment]
@deepalics0044 , did you check the docs?
https://github.com/e-mission/e-mission-docs/search?q=add+new+questions&unscoped_q=add+new+questions

**Comment by shankari** [comment]
In addition to qualtrics, the external survey method will also work for survey monkey (tested once) and google forms (used by tripaware). Or really for any web form which has a unique ID associated with the field for the UUID.

If you have a custom HTML-based survey that you designed, you should be able to pop up that survey and fill in the UUID and trip ID information. You just have to get the `<... id="xxxxx">  fields properly and set them in https://github.com/e-mission/e-mission-phone/blob/master/www/js/survey/launch.js#L113 or https://github.com/e-mission/e-mission-phone/blob/master/www/js/survey/launch.js#L69
