### ISSUE TITLE
Fix the start_time graph to display the histogram of start times + add histogram of durations

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#67]
Instead of using nvd3, you could drop down to the raw d3 and use its histogram.
https://github.com/d3/d3-array/blob/master/README.md#histograms

Or use the `binEntries` from the common code.
Or replace `binEntries` by `Histogram` - no point in rewriting code when there's some nice code out there...

**Comment by shankari** [comment]
@krisma, this is what we discussed yesterday

**Comment by krisma** [comment]
In the histogram for distribution, what are x, y-axis?

**Comment by shankari** [comment]
I assume x = `start hour`, y = `number`.
What do you think?

**Comment by krisma** [comment]
This is informative to users. I just need to figure out how to put many time strings like 18:00 in x-axis in a not-too-compact way

**Comment by krisma** [comment]
Ok I'll use http://nvd3.org/examples/multiBarHorizontal.html with x-axis duration and y-axis starthour

**Comment by shankari** [comment]
oh wait, which graph did you ask this for?
for the start time histogram, we should have start_hour versus number
for the duration, it would be duration versus number

**Comment by shankari** [comment]
flash back to high school :)
https://en.wikipedia.org/wiki/Histogram

**Comment by shankari** [comment]
I am not sure if x-axis duration and y-axis start hour is that useful. What does it show? But you might as well add it and we can remove it based on feedback.

**Comment by krisma** [comment]
duration vs number would be [a1, a2, a3, a4, ...] on x-axis and [1, 1, 1, 1,...] on y isn't it?

**Comment by krisma** [comment]
I thought u suggest to let users know like if I leave at 8am it's gonna take 30min, if I leave at 9 it's gonna take like 60mins on freeway I80 or 580.

**Comment by shankari** [comment]
you can just flip it and do hour on x-axis versus duration on y-axis.
then you can use a line graph since y would be more variable

or do a histogram of x-axis duration (i.e. bin at 15 min or 30 mins intervals)

**Comment by shankari** [comment]
Fixed by #73
