### ISSUE TITLE
List and detail views should include speeds

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#68]
Now that we have picked a charting solution, we should use it.

In particular:
- List view should show mean speed
- Detail view should show speed and distance graphs.

List of speeds is included in the section as seen here.
https://github.com/e-mission/e-mission-server/blob/master/emission/core/wrapper/cleanedsection.py

**Comment by shankari** [comment]
@krisma this is for you

**Comment by krisma** [comment]
Each trip has multiple sections, yet each section still has multiple speeds. Is there smaller unit than section? 
In list view, the mean speed is calculated directly by distance/duration?
In detail view, the speed is the average for all "smaller units in section"?

**Comment by shankari** [comment]
The smaller unit is points. The list of speeds is the instantaneous speed between any two points in the trip. So it can show the variation speed over the course of the trip. For the detail view, you should show a graph of the speed over time for each section (maybe right below the start and end time of the section). Unsure what to show for list view - propose something!

**Comment by krisma** [comment]
We already have a map on list view so using a chart is not an option. we do have space under "1km in 2hr" where we can put the average speed. However, people can easily figure the speed out after they see the "km in hr" thing. To conclude, I don't think we need to show speed in list view.

**Comment by shankari** [comment]
Fixed by #73
